CREATE TABLE CITIZEN (
    citizen_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_citizen PRIMARY KEY (citizen_id),
    CONSTRAINT uq_citizen_email UNIQUE (email)
);

CREATE TABLE OFFICIAL (
    official_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_official PRIMARY KEY (official_id),
    CONSTRAINT uq_official_email UNIQUE (email)
);

CREATE TABLE COMPLAINT (
    complaint_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    citizen_id NUMBER NOT NULL,
    official_id NUMBER,
    category VARCHAR2(50) NOT NULL,
    description VARCHAR2(500) NOT NULL,
    complaint_date DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    official_remarks VARCHAR2(500),
    resolved_date DATE,
    CONSTRAINT pk_complaint PRIMARY KEY (complaint_id),
    CONSTRAINT fk_complaint_citizen
        FOREIGN KEY (citizen_id)
        REFERENCES CITIZEN (citizen_id),
    CONSTRAINT fk_complaint_official
        FOREIGN KEY (official_id)
        REFERENCES OFFICIAL (official_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_complaint_status
        CHECK (status IN ('Pending', 'In Progress', 'Resolved'))
);

COMMIT;